#pragma once

#include <filesystem>
#include <string>

enum class RunMode { eRun, eBytecode, eAst };

struct RunResult
{
    unsigned long exitCode = 0;
    unsigned long long elapsedMs = 0;
    bool timedOut = false;
    bool truncated = false;
    std::string output;
    std::string error;
};

// Runs trusted code via the project's existing Ubuntu/WSL engine. This is not
// an isolation boundary. Source paths are generated by us, never shell text.
RunResult runSource(const std::filesystem::path& root, const std::string& source, RunMode mode);
std::string readUtf8(const std::filesystem::path& path);
void writeUtf8(const std::filesystem::path& path, const std::string& text);
std::wstring widen(const std::string& text);
std::string narrow(const std::wstring& text);
